//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    [AspireExport(ExposeProperties = true)]
    public partial class EFMigrationResource : ApplicationModel.Resource, ApplicationModel.IResourceWithWaitSupport, ApplicationModel.IResource
    {
        public EFMigrationResource(string name, ApplicationModel.ProjectResource projectResource, string? contextTypeName) : base(default!) { }

        public bool BundleSelfContained { get { throw null; } set { } }

        public string? BundleTargetRuntime { get { throw null; } set { } }

        public string? ContextTypeName { get { throw null; } }

        public string? MigrationNamespace { get { throw null; } set { } }

        public string? MigrationOutputDirectory { get { throw null; } set { } }

        public string? MigrationsProjectPath { get { throw null; } set { } }

        public ApplicationModel.ProjectResource ProjectResource { get { throw null; } }

        public bool PublishAsMigrationBundle { get { throw null; } set { } }

        public bool PublishAsMigrationScript { get { throw null; } set { } }

        public bool ScriptIdempotent { get { throw null; } set { } }

        public bool ScriptNoTransactions { get { throw null; } set { } }
    }

    public static partial class EFMigrationResourceBuilderExtensions
    {
        [AspireExport]
        public static ApplicationModel.IResourceBuilder<EFMigrationResource> PublishAsMigrationBundle(this ApplicationModel.IResourceBuilder<EFMigrationResource> builder, string? targetRuntime = null, bool selfContained = false) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<EFMigrationResource> PublishAsMigrationScript(this ApplicationModel.IResourceBuilder<EFMigrationResource> builder, bool idempotent = false, bool noTransactions = false) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<EFMigrationResource> RunDatabaseUpdateOnStart(this ApplicationModel.IResourceBuilder<EFMigrationResource> builder) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<EFMigrationResource> WithMigrationNamespace(this ApplicationModel.IResourceBuilder<EFMigrationResource> builder, string @namespace) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<EFMigrationResource> WithMigrationOutputDirectory(this ApplicationModel.IResourceBuilder<EFMigrationResource> builder, string outputDirectory) { throw null; }

        [AspireExport("withMigrationsProjectFromPath", MethodName = "withMigrationsProject", Description = "Configures a separate project containing the migrations using a path")]
        public static ApplicationModel.IResourceBuilder<EFMigrationResource> WithMigrationsProject(this ApplicationModel.IResourceBuilder<EFMigrationResource> builder, string projectPath) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<EFMigrationResource> WithMigrationsProject<TProject>(this ApplicationModel.IResourceBuilder<EFMigrationResource> builder)
            where TProject : IProjectMetadata, new() { throw null; }
    }

    public static partial class EFResourceBuilderExtensions
    {
        [AspireExportIgnore(Reason = "Action<IResourceBuilder<DotnetToolResource>> callbacks are not ATS-compatible.")]
        public static ApplicationModel.IResourceBuilder<EFMigrationResource> AddEFMigrations(this ApplicationModel.IResourceBuilder<ApplicationModel.ProjectResource> builder, string name, System.Action<ApplicationModel.IResourceBuilder<ApplicationModel.DotnetToolResource>>? configureToolResource) { throw null; }

        [AspireExportIgnore(Reason = "Action<IResourceBuilder<DotnetToolResource>> callbacks are not ATS-compatible.")]
        public static ApplicationModel.IResourceBuilder<EFMigrationResource> AddEFMigrations(this ApplicationModel.IResourceBuilder<ApplicationModel.ProjectResource> builder, string name, string contextTypeName, System.Action<ApplicationModel.IResourceBuilder<ApplicationModel.DotnetToolResource>>? configureToolResource) { throw null; }

        [AspireExport("addEFMigrationsWithContextType", MethodName = "addEFMigrations", Description = "Adds EF Core migration management for a specific DbContext type identified by name")]
        public static ApplicationModel.IResourceBuilder<EFMigrationResource> AddEFMigrations(this ApplicationModel.IResourceBuilder<ApplicationModel.ProjectResource> builder, string name, string contextTypeName) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<EFMigrationResource> AddEFMigrations(this ApplicationModel.IResourceBuilder<ApplicationModel.ProjectResource> builder, string name) { throw null; }
    }
}